version: '3'
services:
    mysql:
      image: mysql:5.7
      container_name: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=Mrk_9626
        - MYSQL_DATABASE=atms
        - MYSQL_PASSWORD=Mrk_9626

    loader:
      image: ing-atms-locator/loader:latest
      container_name: loader
      environment:
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: Mrk_9626
      links:
        - mysql
      ports:
        - 8082:8082
      command: ./docker-enterypoint.sh "mysql" "mysql" "3306" "./loader.jar" "docker"


    web:
      image: ing-atms-locator/web:latest
      container_name: web
      depends_on:
        - loader
      environment:
        DB_HOST: mysql
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: Mrk_9626
      links:
        - loader
        - mysql
      ports:
        - 8081:8081
      command: ./docker-enterypoint.sh "loader" "loader" "8082" "./web.war" "docker"

